USE sakila;
-- SUM(): PARA SUMAS
-- AVG(): PARA PROMEDIOS
-- COUNT(): PARA CONTAR

SELECT * FROM payment;

SELECT customer_id, amount FROM payment;

-- COUNT()
SELECT COUNT(*) AS 'CANTIDAD DE FILAS' FROM payment;
SELECT COUNT(*) AS 'CANTIDAD DE PAISES' FROM world.country;

-- CANTIDAD DE VENTAS QUE TUVO EL TRABAJADOR 2
SELECT COUNT(*) FROM payment WHERE staff_id = 2;

-- CANTIDAD DE CLIENTES DISTINTOS
SELECT COUNT(DISTINCT customer_id) AS 'CLIENTES' FROM payment;

-- SUM() 
SELECT SUM(amount) AS 'TOTAL DE RENTAS' FROM payment;
SELECT SUM(amount) AS 'TOTAL DE RENTAS' FROM payment WHERE staff_id = 2;

-- ¿CUAL CLIENTE REALIZÓ MÁS RENTAS? 
-- R: CLIENTE 148
SELECT customer_id, COUNT(*) AS TOTAL_DE_RENTAS FROM payment GROUP BY customer_id ORDER BY TOTAL_DE_RENTAS DESC;

-- GROUP BY: GENERA GRUPOS BASADO EN LA COLUMNA DADA
-- ORDER BY: ORDENA DE FORMA ASC / DESC LA COLUMNA INDICADA
SELECT staff_id, SUM(amount) AS 'TOTAL DE RENTAS' FROM payment GROUP BY staff_id;

-- ¿CUAL CLIENTE GASTO MAS?
SELECT customer_id, SUM(amount) AS TOTAL FROM payment GROUP BY customer_id ORDER BY TOTAL DESC;

-- AVG()
SELECT AVG(amount) AS Promedio FROM payment;

-- ¿CUAL CLIENTE GASTO MAS, EN PROMEDIO?
SELECT customer_id, AVG(amount) AS PROMEDIO_DE_RENTAS FROM payment GROUP BY customer_id ORDER BY PROMEDIO_DE_RENTAS DESC;
